### PR TITLE
Update to references

### PR DESCRIPTION
**Pull request by hagenw**
This includes:
1.) Update the references to the source image model from #42 to be in line with #46 by moving them to the extra `doc/references.rst` file
2.) Cleaning up `doc/references.rst` by introducing line breaks
3.) Fixing a typo

### CODE REVIEW

**Comment by hagenw** [comment]
If you do a citation in a paper you would use "Name1" for one author "Name1 and Name2" for two authors and "Name1 et al." for three or more authors. That was the idea behind the referencing and it is the same as in SFS theory.

But I agree that most probably it would be better to use just one name here as I'm also not willing to add "etal" into the brackets. I will merge this first and then think again about it.

**Comment by mgeier** [comment]
Yes, "Name1 and Name2 (2007)" or "(Name1 and Name2, 2007)" would be fine, but "[Name1Name22007]" is an entirely different thing.

Did you ever try https://github.com/mcmtroffaes/sphinxcontrib-bibtex?

**Comment by hagenw** [comment]
I thought about it, but I never tried. It is also a little bit [buggy using multiple pages](http://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html#unresolved-citations-across-documents), but I will give it a try.

**Comment by mgeier** [comment]
I wasn't aware of the multi-page issue, but using `:all:` doesn't sound too bad, does it?
Why would we want to have unused entries in our bibtex file anyway?

**Pull request merged**
