### PR TITLE
introduce new wfs 2.5D point source time domain driving function

### PR DESCRIPTION
**Pull request by fs446**
As we introduced a new 2.5D WFS point source driving function in frequency domain with version 0.5.0 we should do this in time frequency as well for consistency, I'd propose.
Thus, for time domain same idea as for frequency domain: putting the new version into `point_25D()` (this is the 3D->2.5D Delft approach) and creating `point_25d_legacy()` that holds the function which was used up to <=0.6.0 (this is the 2D -> 2.5D approach by Rabenstein/Spors).

Furthermore, some minor corrections in the math docstrings for the other time domain WFS functions and some pep8 issues fixed.

I would suggest to create a 0.6.1 minor release to introduce the new feature.

### CODE REVIEW

**Comment by hagenw** [comment]
You have to merge https://github.com/sfstoolbox/sfs-python/pull/169 first in order to fix the CI error.

**Comment by fs446** [comment]
Thanks for fixing things beforehand in #169! This PR is now updated by rebase.

**Review by hagenw — APPROVED** [review]
Great, thanks for the effort.

**Comment by fs446** [comment]
I re-opened this PR to improve and correct some docstring passages and to allow further double check / review. Thanks!

**Comment by hagenw** [comment]
I thik you have to create a bew pull request as you cannot merge here.

**Pull request merged**
