### PR TITLE
Use sfs.default object instead of sfs.defs submodule

### PR DESCRIPTION
**Pull request by mgeier**
See #32.

### CODE REVIEW

**Comment by hagenw** [comment]
I like your changes :+1: 

Would be great if you could integrate them in the documentation as well. I think it would be nice if we tell a user how she/he could change the default speed of sound.

**Comment by mgeier** [comment]
What about 8564d71a70aa7f76e835bd3f9269e2a1fad2ab1c?

I was hesitating to add this to the docs, because it's a bit messy.

Does anyone have an idea how to do this in a cleaner way?

**Comment by mgeier** [comment]
#45 and #69 should be merged before this PR because they use `sfs.defs` a few times.

**Comment by mgeier** [comment]
I've moved the `autosummary`directive in a4c7c8c2d35f130bb4768e63af20f99df509d166.

This way, `sfs.default` is documented directly on the main API page and not on a separate page.

I think that's better.

Any other opinions?

**Pull request merged**
