### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by hagenw**
In the Matlab version and on the homepage I used the phrase `SFS Toolbox Team` for the copyright statements and would propose to use the same in the Python version.

### CODE REVIEW

**Comment by mgeier** [comment]
Is there a precedent for this?

**Comment by hagenw** [comment]
Developers suggest more that you have worked on the code, but there are some people that work only on the documentation or maybe the web page. That's the reason why I would prefer Team instead.

**Comment by mgeier** [comment]
So there is no precedent?

Both NumPy and SciPy use "Developers".

"Team" sounds very exclusive, and a bit like a company is behind the whole thing, "Developers" puts the focus on the individuals.

Also, currently there is nobody that only works on the documentation. And I don't think there will be anytime soon.
The web page http://sfs.readthedocs.io/ is generated from content written by the SFS developers, the content of the web site http://sfstoolbox.org/ is not generated from content of this repository.

Therefore: I'm very much against "Team". :-1:

If you don't like "Developers", what about "Contributors"?
It would still be nice to have a precedent, but I think I've seen "XYZ Contributors" somewhere before ...

**Comment by hagenw** [comment]
Here are two precedents:
https://raw.githubusercontent.com/nodejs/node/master/LICENSE
https://raw.githubusercontent.com/mockito/mockito/master/LICENSE
It seems to be that they use the lower case version "contributors".

I liked with "Team" that it is short, but I can understand your complains.
I changed the commit in this pull request to use "contributors" which I still find a little bit better than "Developers".

**Comment by mgeier** [comment]
JavaScript and Java projects are *definitely not* valid sources for inspiration with regards to anything even remotely related to style or taste!

**Comment by mgeier** [comment]
Those are some examples I found:

* NumPy Developers
* SciPy Developers
* IPython Development Team
* Jupyter Development Team
* Sphinx team
* authors of Vispy
* Kivy Team and other contributors

I still don't see any reason to change what we currently use.

**Comment by hagenw** [comment]
One of the reasons is that we use something different on the web page and the Matlab version.
But as the easiest way seems to be to change it there, I will switch to `.SFS Toolbox Developers` there.

BTW, you should update the year in the LICENSE file of sfs-python.

**Comment by mgeier** [comment]
An interesting discussion from the Jupyter project: https://groups.google.com/forum/#!msg/jupyter/vZpWgw8zKdc/2P27jQlaBAAJ

It looks like they'll change their copyright notice to "Project Jupyter Contributors".

**Pull request closed without merging**
