### PR TITLE
Fix non-unit direction vectors

### LINKED ISSUE #20: Handling of directional vector for plane waves
At the moment we can change the frequency of the resulting sound field of a plane wave by using non unity vectors for specifying the direction. I don't know if this is desired behavior, but I would suggest to change it to at least raise a warning or an error. Or maybe to some automatic normalization of the directional vector.

```python
import numpy as np
import matplotlib.pyplot as plt
import sfs

grid = sfs.util.xyz_grid([-2, 2], [-2, 2], 0, spacing=0.01)
x0 = 0, 0, 0
npw = 0, -1, 0
f = 1000
omega = 2 * np.pi * f
p_plane = sfs.mono.source.plane(omega, x0, npw, grid);
sfs.plot.soundfield(p_plane, grid);
plt.title('Plane wave with npw = {}'.format(npw));
plt.savefig('pw1.png')

npw = 0, -2, 0
p_plane = sfs.mono.source.plane(omega, x0, npw, grid);
sfs.plot.soundfield(p_plane, grid);
plt.title('Plane wave with npw = {}'.format(npw));
plt.savefig('pw2.png')
```

pw1

pw2

### PR DESCRIPTION
**Pull request by hagenw**
This tries to fix #20 and #28.

I renamed `util.normal_vector()` to `util.normalize_vector()` as proposed in #28 and used it for every single dimensional direction vector `n`. The field plotted in #20 looks now correct with this.

I'm still not happy with the naming, which I will discuss directly in #28 and there is the problem how to handle several unit vectors at once like `n0 = util.asarray_of_rows(n0)`.

### CODE REVIEW

**Comment by mgeier** [comment]
Any objections?
If not, LGTM!

**Comment by hagenw** [comment]
Just a reminder, the fix is not done for `n0 = util.asarray_of_rows(n0)` as I didn't know what is the best way to apply it there. With a loop? Can someone help out with this?

**Comment by mgeier** [comment]
If this would be needed only once, you could do something like:

```python
n0 = util.asarray_of_rows(n0)
n0 = np.row_stack([util.normalize_vector(n) for n in n0])
```

But since we need this several times, we should make a function.

Should we include this into `util.normalize_vector()`?
We could do a simple `np.asarray()` and then do different things for one and two-dimensional arrays.
This could be used like `util.normalize_vector(util.asarray_of_rows(n0))`

Or should we make a new function `util.asarray_of_normalized_rows()`?
This has the problem of #28, could be both types of "normalization".

In a separate function, you could use something like this:

```python
# make sure x is a 2-dimensional array
x / np.linalg.norm(x, axis=1, keepdims=True)
```

However, note that the `keepdims` argument is only available since NumPy 1.10.0 (see https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.norm.html).

This should do the same thing and also work for older versions:

```python
# make sure x is a 2-dimensional array
x / np.linalg.norm(x, axis=1).reshape(-1, 1)
```

**Comment by mgeier** [comment]
PS: if we include this in `util.normalize_vector()`, it will lose its squeezing ability.
This means we would have to use `util.normalize_vector(util.asarray_1d(n))` in many cases.

Which would be a bit longer, but it would actually be more explicit, which generally is a good thing.

Another problem: we would have to decide between `normalize_vector()` and `normalize_vectors()`.

BTW, if we decide for some fundamental changes along the lines of #36, we'll have to change those functions again.

**Comment by mgeier** [comment]
PPS: We can also implement this later, we should just create a new issue as a reminder.

**Comment by hagenw** [comment]
At the beginning I was also thinking of two functions similar to the `asarray` once, e.g.
```python
util.asdirection()
util.asdirections()
```
But maybe it is better to have to use it in an explicit way?
```python
util.normalize_vector(util.asarray_1d(n))
util.normalize_vector(util.asarray_of_rows(n))
```

**Comment by mgeier** [comment]
I would suggest to merge this PR as is and postpone further changes until we see how our understanding of a "direction" evolves.

**Comment by hagenw** [comment]
Fine with me, I created an issue for the remaining TODO of this PR.

**Pull request merged**
